# paths to include during linting. `--path` is ignored if present.
disabled_rules:
  - trailing_whitespace
  - force_cast
  - line_length
  - function_body_length
  - identifier_name
  - force_try
  - type_name
  - shorthand_operator
  - file_length
  - unneeded_override
  - control_statement
  - switch_case_alignment

included: 
  - dota-heroes
  - dota-heroesTests

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - Pods