# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'dota-heroes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  pod 'SnapKit', '5.6.0'
  pod 'SwiftLint', '0.39.1'
  pod 'Moya'
  # Pods for dota-heroes

  target 'dota-heroesTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
  end

end
